spring:
  application:
    name: telegram-ingestion-service
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/admin
    username: monitoring
    password: monitoring123
  
  rabbitmq:
    host: localhost
    port: 5672
    username: monitoring
    password: monitoring123

server:
  port: 8083

ingestion:
  queue:
    name: telegram-events
  mock:
    enabled: true
    interval-seconds: 5

logging:
  level:
    ua.edu.ucu.de.fp.monitoring: DEBUG
