spring:
  application:
    name: group-management-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: monitoring
    password: monitoring123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true

server:
  port: 8081

logging:
  level:
    ua.edu.ucu.de.fp.monitoring: DEBUG
